### ISSUE TITLE
Icon versioning over complicated and not working

### ISSUE THREAD

**Issue by revolter** [krzysztofzablocki/KZBootstrap#43]
I don't understand why the icon versioning script is so complicated and how do you guys use it when it's not working.

Firstly, why does it search certain files with some (iPad) exception instead of finding all the `AppIcon*.png` files?

Secondly, it's not working on iPad, at all! There is the comment:

    # Workaround to fix issue#16 to use wildcard * to actually find the file

which points to #16 which isn't related to this at all. And the `find` fails with `find: AppIcon72x72~ipad.png: unknown primary or operator` error, so the icon is not versioned on iPad. Changing those lines to:

    processIcon "AppIcon72x72~ipad.png"
    processIcon "AppIcon72x72@2x~ipad.png"
    processIcon "AppIcon76x76~ipad.png"
    processIcon "AppIcon76x76@2x~ipad.png"

fixes it.

**Comment by krzysztofzablocki** [comment]
This comment was referenced to old version of this script, I wrote the first original icon versioning script under a different project couple of years back https://github.com/krzysztofzablocki/IconOverlaying
 
In regard to complexity of it, It's not easy, but it's simple:
- Makes sure you have all required dependencies e.g. image magick and ghost script
- Ensures it has proper content to render onto the icon
- Has to deal with different variations of icon configuration, this predates the .xcassets folders
- Has to create tmp images and cleanup since original content should not be modified
- Should not perform actions for release builds
- Have to apply image magick logic which takes many lines to render in a way we want
- Have to pngcrush to work properly
- Has to read plist file

In regards to iPad support though, you are right, this is messed up, but your solution isn't ideal either,I just pushed an updated version that should work nicer, let me know if it works for you @revolter

**Comment by revolter** [comment]
Well, I understand now why is it like this. But I think it should be changed to reflect the latest Xcode versions. But I do have some questions regarding this workflow, which I changed (and I think, improved) for myself:

1. Regarding image magick and ghost script, why not try to install them too? I achieved it like this:

	brewPath=`which brew`
	echo ${brewPath}

	convertPath=`which convert`
	echo ${convertPath}
	if [[ ! -f ${convertPath} || -z ${convertPath} ]]; then
		if [[ -f ${brewPath} && ! -z ${brewPath} ]]; then
			brew install imagemagick
		else
			echo "WARNING: Skipping Icon versioning, you need to install ImageMagick, you can use brew to simplify process: brew install imagemagick"

			exit 0;
		fi
	fi

	gsPath=`which gs`
	echo ${gsPath}
	if [[ ! -f ${gsPath} || -z ${gsPath} ]]; then
		if [[ -f ${brewPath} && ! -z ${brewPath} ]]; then
			brew install ghostscript
		else
			echo "WARNING: Skipping Icon versioning, you need to install ghostscript (fonts) first, you can use brew to simplify process: brew install ghostscript"

			exit 0;
		fi
	fi

2. Regarding release builds, why not use:

	if [ $CONFIGURATION = "Release" ]; then
		exit 0
	fi

right at the start of the script?

3. Why does it have to read plist file? This is related to my "finding all the `AppIcon*.png` files" initial question.

And yes, your solutions works too.

**Comment by krzysztofzablocki** [comment]
I wouldn't install image magick for the user, this is a little too intrusive for a script like this, but the point of moving the release to top of the script is a good one. 

As for icons, we only process those that are used for real icons, my version removes that hacky workaround for iPad icons, purely using what the Xcode uses for real icons, this is safer.

If you have improvements to the script, I'd be happy to accept PR with them :)
